### ISSUE TITLE
Changes in the API integration state are not applied until next time the app is restarted

### ISSUE THREAD

**Issue by txelu** [tgudelj/MATRICIntegrationDemo#1]
To reproduce: 
* Start with **3rd party integration** setting disabled.
* Enable that seting, save the changes and close the editor window (it will be minimized into the taskbar)

At this point the 3rd party integration is still not enabled. In fact, my application crashes due to an exception (`System.Net.Sockets.SocketException: 'Se ha forzado la interrupción de una conexión existente por el host remoto'`) that cannot be caught because it happens internally in the `MatricIntegration.dll`.

To fix it I must quit Matric (using the `Quit` command on the taskbar icon) and lauching Matric again. After that my application correctly connects or request a new PIN if not yet configured.

**Comment by tgudelj** [comment]
Fixed: Fix will be included in the next release
